#!/bin/sh

if [ ! -f ./qleverui.sqlite3 ]; then
    echo "qleverui.sqlite3 not found, copying default from /usr/share/qlever-ui/."
    echo "The state of this development instance is persisted in qleverui.sqlite3."
    cp /usr/share/qlever-ui/qleverui.sqlite3 ./qleverui.sqlite3
fi
set -a
. /etc/qlever-ui/qlever-ui.env
set +a
export QLEVERUI_DATABASE_URL=sqlite:////$(pwd)/qleverui.sqlite3
/opt/venvs/qlever-ui/bin/gunicorn \
    qlever.wsgi:application \
    --bind 0.0.0.0:8176 \
    --workers 4 \
    --timeout 120 \
    --limit-request-line 10000