#!/bin/sh
set -a
[ -f /etc/qlever-ui/qlever-ui.env ] && . /etc/qlever-ui/qlever-ui.env
set +a
DJANGO_SETTINGS_MODULE="${DJANGO_SETTINGS_MODULE:-qlever.settings}"
export DJANGO_SETTINGS_MODULE
exec /opt/venvs/qlever-ui/bin/python -m django "$@"
